# -*- coding: utf-8 -*-
"""notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12taBIeGvlBwoY-VasjXG5nso-tT7Sp2L

<center><img src="redpopcorn.jpg"></center>

**Netflix**! What started in 1997 as a DVD rental service has since exploded into one of the largest entertainment and media companies.

Given the large number of movies and series available on the platform, it is a perfect opportunity to flex your exploratory data analysis skills and dive into the entertainment industry.

You work for a production company that specializes in nostalgic styles. You want to do some research on movies released in the 1990's. You'll delve into Netflix data and perform exploratory data analysis to better understand this awesome movie decade!

You have been supplied with the dataset `netflix_data.csv`, along with the following table detailing the column names and descriptions. Feel free to experiment further after submitting!

## The data
### **netflix_data.csv**
| Column | Description |
|--------|-------------|
| `show_id` | The ID of the show |
| `type` | Type of show |
| `title` | Title of the show |
| `director` | Director of the show |
| `cast` | Cast of the show |
| `country` | Country of origin |
| `date_added` | Date added to Netflix |
| `release_year` | Year of Netflix release |
| `duration` | Duration of the show in minutes |
| `description` | Description of the show |
| `genre` | Show genre |
"""

# Importing pandas and matplotlib
import pandas as pd
import matplotlib.pyplot as plt

# Read in the Netflix CSV as a DataFrame
netflix_df = pd.read_csv("netflix_data.csv")

#Filter the DataFrame
only_movies = netflix_df[netflix_df['type']=='Movie']
less_than_two_k = only_movies[only_movies['release_year']<2000]
movies_in_the_nineties = less_than_two_k[less_than_two_k['release_year']>=1990]

#Plot the chart with histogram
plt.hist(movies_in_the_nineties['duration'])
plt.title('Distribution of movies duration in the 90s')
plt.xlabel('Duration')
plt.ylabel('# of Movies')
plt.show()

#Estimation of most popular duration
duration = 100

#Filter the Action movies
action_movies = movies_in_the_nineties[movies_in_the_nineties['genre'] == 'Action']

#Count the short Action movies
short_movie_count = 0

for dur in action_movies['duration']:
    if dur < 90:
        short_movie_count += 1
    else:
        short_movie_count += 0

print(short_movie_count)